# SPDX-FileCopyrightText: 2006-2024 Knut Reinert & Freie Universität Berlin
# SPDX-FileCopyrightText: 2016-2024 Knut Reinert & MPI für molekulare Genetik
# SPDX-License-Identifier: CC0-1.0

name: Coverage

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: coverage-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name != 'push' }}

env:
  TZ: Europe/Berlin

defaults:
  run:
    shell: bash -Eexuo pipefail {0}

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ubuntu-22.04
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "gcc13"
            compiler: "gcc-13"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup toolchain
        uses: seqan/actions/setup-toolchain@main
        with:
          compiler: ${{ matrix.compiler }}
          ccache_size: 125M

      - name: Install CMake
        uses: seqan/actions/setup-cmake@main
        with:
          cmake: 3.25.3

      - name: Install gcovr
        run: |
          sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/${CC/gcc/gcov} 100
          pip install gcovr==6.0

      - name: Configure
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Debug \
                   -DCMAKE_CXX_FLAGS="--coverage -fprofile-arcs -ftest-coverage -Werror" \
                   -DCMAKE_C_FLAGS="--coverage -fprofile-arcs -ftest-coverage -Werror" \
                   -DCMAKE_EXE_LINKER_FLAGS="-Wl,-lgcov" \
                   -DCMAKE_SHARED_LINKER_FLAGS="-Wl,-lgcov"

      - name: Build and run tests
        run: |
          cd build
          make -j2 -k check

      - name: Generate coverage report
        run: |
          gcovr --gcov-executable ${{ github.workspace }}/.github/workflows/scripts/gcov.sh \
                --root ${{ github.workspace }} \
                ${{ github.workspace }}/build \
                --filter ${{ github.workspace }}/include \
                --filter ${{ github.workspace }}/src \
                --exclude-unreachable-branches \
                --exclude-throw-branches \
                --exclude-noncode-lines \
                -j 2 \
                --xml \
                --output ${{ github.workspace }}/build/coverage_report.xml

      - name: Submit coverage build
        uses: codecov/codecov-action@v3
        with:
          files: ${{ github.workspace }}/build/coverage_report.xml
          fail_ci_if_error: false
